# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    avoid_print: true
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# DCM (Dart Code Metrics) configuration
dcm:
  rules:
    - avoid-dynamic
    - avoid-assignments-as-conditions
    - avoid-casting-to-extension-type
    - avoid-cascade-after-if-null
    - avoid-unused-parameters
    - prefer-conditional-expressions
    - prefer-first
    - prefer-correct-test-file-name
    - avoid-collection-methods-with-unrelated-types
    - avoid-conditions-with-boolean-literals
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-duplicate-mixins
    - avoid-duplicate-test-assertions
    - avoid-empty-spread
    - avoid-explicit-pattern-field-name
    - avoid-generics-shadowing
    - avoid-missed-calls
    - avoid-misused-set-literals
    - avoid-nested-records
    - avoid-nullable-tostring
    - avoid-passing-async-when-sync-expected
    - avoid-passing-self-as-argument
    - avoid-redundant-async
    - avoid-self-assignment
    - avoid-throw-in-catch-block
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - no-empty-block
    - no-equal-then-else
    - prefer-iterable-of
    - prefer-match-file-name
    - always-remove-listener
    - avoid-incomplete-copy-with
    - avoid-incorrect-image-opacity
    - provide-image-semantic-label
    - avoid-unnecessary-setstate
    - avoid-unnecessary-stateful-widgets
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-single-widget-per-file
    - use-setstate-synchronously
